---
version: 2
project_name: slackmoji-notifier

before:
  hooks:
    - go mod download

builds:
  - id: slackmoji-notifier
    binary: slackmoji-notifier
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w"
      - "-X github.com/particledecay/slackmoji-notifier/pkg/build.Version={{ .Version }}"
      - "-X github.com/particledecay/slackmoji-notifier/pkg/build.Date={{ .Date }}"

archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}-
      {{- .Version }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
