{{- if .Values.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slackmoji-notifier.fullname" . }}
  labels:
    {{- include "slackmoji-notifier.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_BOT_TOKEN: {{ .Values.secret.slack.botToken | b64enc }}
  SLACK_APP_TOKEN: {{ .Values.secret.slack.appToken | b64enc }}
  OPENAI_API_KEY: {{ .Values.secret.openai.apiKey | b64enc }}
{{- end }}
